apiVersion: v1
kind: Service
metadata:
  name: myapp-nginx
  namespace: myapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: myapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.myapp_service.nodeport }}